### ISSUE TITLE
API broken in youtube-dl-server:yt-dlp image

### ISSUE THREAD

**Issue by redec** [nbr23/youtube-dl-server#116]
When POST'ing a url to `/api/downloads` it's failing with a 500 now. It looks like there's a dependency missing...I will look into fixing it myself at some point when I have a few spare cycles, but I figured I'd enter an issue in the meantime. Thanks!

Here's the log:
```
INFO:     192.168.0.231:58226 - "POST /api/downloads HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
     File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/ydl_server/views.py", line 196, in api_queue_download
    data = await request.form()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/requests.py", line 260, in _get_form
    parse_options_header is not None
AssertionError: The `python-multipart` library must be installed to use form parsing.
```

**Comment by nbr23** [comment]
hi @redec, thanks for the report and sorry for the delay!
I published a fix adding that dependency.
I'm curious about how you found this issue though. This is a legacy way of sending the POST requests that the app shouldn't be using. Are you using `curl` or some other tool to submit urls?
If you're using curl, please check the readme, it has an updated command for this.
https://github.com/nbr23/youtube-dl-server/blob/master/README.md#curl

**Comment by redec** [comment]
Hi @nbr23 thanks for this awesome utility! 

I have an iPhone shortcut setup which (from the browser) I can tap "Send to YouTube-dl" and it automatically posts the current url via the api...it has worked really nice for a long time :).  Just now I looked into updating it to the new format and unfortunately it doesn't seem there's an easy way to post json content-type from an iPhone shortcut.  I will have to spend a little more time on it, it must be possible somehow...one would think.  Thanks for the update! 🙏

**Comment by nbr23** [comment]
Oh ok I see. Well hopefully the fix I pushed will work for you then! Let me know if not.
Cheers!

**Comment by redec** [comment]
The API is working great now, thanks. 🙏   For what it's worth I have also gotten my shortcut working posting json, so both ways work nicely now 😁

**Comment by nbr23** [comment]
Fantastic! Thx for the update!
