### ISSUE TITLE
Container startup blocker

### ISSUE THREAD

**Issue by 4oijq342** [nbr23/youtube-dl-server#125]
Hello,
I am receiving this error on this image:
docker.io/nbr23/youtube-dl-server:latest `sha256:dced1428278b7ee6da13c1979c4ec77a92c1db00e0241a2d9ff456a220bf3744`

```
2024-11-18T08:40:59.976181170Z Using configuration file /app_config/config.yml
2024-11-18T08:40:59.982057657Z Migrating database from version 1
2024-11-18T08:40:59.986524955Z Traceback (most recent call last):
2024-11-18T08:40:59.987434182Z   File "/usr/src/app/./youtube-dl-server.py", line 29, in <module>
2024-11-18T08:40:59.987444116Z     app.state.ydlhandler = YdlHandler(app_config, app.state.jobshandler)
2024-11-18T08:40:59.987447609Z                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-18T08:40:59.987450519Z   File "/usr/src/app/ydl_server/ydlhandler.py", line 84, in __init__
2024-11-18T08:40:59.987453497Z     self.import_ydl_module()
2024-11-18T08:40:59.987456194Z     ~~~~~~~~~~~~~~~~~~~~~~^^
2024-11-18T08:40:59.987458845Z   File "/usr/src/app/ydl_server/ydlhandler.py", line 41, in import_ydl_module
2024-11-18T08:40:59.987461563Z     ydl_module = importlib.import_module(
2024-11-18T08:40:59.987463944Z         os.environ.get("YOUTUBE_DL").replace("-", "_")
2024-11-18T08:40:59.987466631Z     )
2024-11-18T08:40:59.987469052Z   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
2024-11-18T08:40:59.987474235Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-18T08:40:59.987477028Z            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-18T08:40:59.987479801Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-11-18T08:40:59.987482617Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-11-18T08:40:59.987485419Z   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
2024-11-18T08:40:59.987519391Z ModuleNotFoundError: No module named 'youtube_dl'
```

This is causing the container to restart in an infinite loop.

Any advice for troubleshooting this?

**Comment by nbr23** [comment]
hi, the default image `nbr23/youtube-dl-server:latest` now uses yt-dlp and not youtube-dl (cf https://github.com/nbr23/youtube-dl-server/issues/124).
Either use `nbr23/youtube-dl-server:youtube-dl`, or make sure you are not passing `YOUTUBE_DL=youtube-dl` to the container if using `nbr23/youtube-dl-server:latest`
