### ISSUE TITLE
Accepts URL but then doesn't function.

### ISSUE THREAD

**Issue by Leopere** [nbr23/youtube-dl-server#21]
```bash
docker service logs -f yt_youtube-dl
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Using youtube-dl module
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Outdated jbos table, cleaning up and recreating
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Started download thread
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Started jobs manager thread
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Updating youtube-dl to the newest version
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Bottle v0.12.19 server starting up (using WSGIRefServer())...
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Listening on http://0.0.0.0:8080/
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Hit Ctrl-C to quit.
yt_youtube-dl.1.z9q2lf1h54lf@t1    |
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Exception in thread Thread-1:
yt_youtube-dl.1.z9q2lf1h54lf@t1    | Traceback (most recent call last):
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/local/lib/python3.9/threading.py", line 950, in _bootstrap_inner
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     self.run()
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/local/lib/python3.9/threading.py", line 888, in run
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     self._target(*self._args, **self._kwargs)
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/src/app/ydl_server/ydlhandler.py", line 67, in worker
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     rc, log = update()
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/src/app/ydl_server/ydlhandler.py", line 86, in update
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     reload_youtube_dl()
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/src/app/ydl_server/ydlhandler.py", line 76, in reload_youtube_dl
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     importlib.reload(sys.modules[module])
yt_youtube-dl.1.z9q2lf1h54lf@t1    |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 168, in reload
yt_youtube-dl.1.z9q2lf1h54lf@t1    |     raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
yt_youtube-dl.1.z9q2lf1h54lf@t1    | ModuleNotFoundError: spec not found for the module 'youtube_dl.extractor.spiegeltv'
```
Container startup logs not sure what's broken here, I'm not a python guy.

**Comment by nbr23** [comment]
Hello @Leopere,
This looks more like an issue with youtube-dl and a specific extractor (for spiege tv here).
Hopefully this gets fixed with newer versions of youtube-dl.
If you have a link to share, I can look further.
Cheers!

**Comment by Leopere** [comment]
Seemed like the YouTube-dl update doesn’t happen.

**Comment by nbr23** [comment]
Can you share a URL so I have a look?
Thanks!

**Comment by Leopere** [comment]
I’d like to not make it public and I’m not sure github has a private
message option for some reason still.

**Comment by nbr23** [comment]
No problem @Leopere, I understand.
I have found some test URLs in the youtube-dl test scenarios and I think I found the issue and should be able to push a fix shortly.
Thanks!

**Comment by nbr23** [comment]
The issue seems to have been that youtube-dl-server by default uses `bestvideo` as format, which does not seem to exist in spiegeltv/spiegel.de. https://github.com/nbr23/youtube-dl-server/commit/933072954b5e5c0075b5169257f03a50f8f17bb0 fixes this by defaulting to `best` instead, which makes much more sense.

I have tried with a few spiegel urls after applying this fix and it seems to be working fine.
Let me know if this works for you as well.

Thanks!
