### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by helmut72** [nbr23/youtube-dl-server#90]
Since some versions I get this error, when using the bookmarklet. My public ip is redacted with 1.1.1.1

```
INFO:    1.1.1.1:0 - "POST /api/downloads HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/ydl_server/views.py", line 145, in api_queue_download
    data = await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm using your latest docker image and it's behind my reverse proxy. I don't have changed anything on my reverse proxy for other reasons, only updating youtube-dl-server with watchtower.

**Comment by helmut72** [comment]
Looks like it's the bookmarklet. The one in the app and in the readme doesn't work. This looks better:

```
javascript:fetch('https://my.server.url/api/downloads',{method: 'POST',body: JSON.stringify({'url': location.href,'format':'video/best'}),headers: {'Content-Type': 'application/json'}});
```

Don't know if it's ok. I know nothing about Javascript.  At least it works.

**Comment by nbr23** [comment]
Thanks, should be fixed with https://github.com/nbr23/youtube-dl-server/commit/79569b2a9be53be7553d470a50bd583e771992c5

**Comment by helmut72** [comment]
Thank you!

**Comment by steff75** [comment]
What would be a current working bookmarklet for the **plain text version**?

With the version from the readme I get an "Internal Server Error".

Thanks!

**Comment by nbr23** [comment]
Hi @steff75 thanks, it's now fixed.
In the future, don't hesitate to open new issues for this kind of things, so it doesn't get missed in a closed issue.
Thanks!
